inherit_from: .rubocop_todo.yml

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - lib/tasks/*
    - bin/webpack
    - bin/webpack-dev-server

Metrics/BlockLength:
  Exclude:
    - spec/**/*
